import { acc1, acc2, acc3, acc4, apple1, apple2, apple3, apple4, audio1, audio2, audio3, audio4, chair1, chair2, chair3, chair4, monitor1, monitor2, monitor3, monitor4, monitor5, monitor6, monitor7, monitor8, table1, table2, table3, table4 } from '../assets/Images'

export const items = [
    { id: 1, 
      name: 'Electric Table', 
      price: 35000,
      color: 'red', 
      vendor: 'hp', 
      category: 'A', 
      quality: 'high', 
      image: table1
    },
    { id: 2, 
      name: 'Electric Home Desk', 
      price: 30000,
      color: 'blue', 
      vendor: 'apple', 
      category: 'B', 
      quality: 'medium', 
      image: table2
    },
    { id: 3, 
      name: 'Office Desk', 
      price: 30000, 
      color: 'yellow', 
      vendor: 'tecno', 
      category: 'C', 
      quality: 'low', 
      image: table3
    },
    { id: 4, 
      name: 'Single Desk For Ease',
      price: 30000, 
      color: 'green', 
      vendor: 'hp', 
      category: 'A', 
      quality: 'medium', 
      image: table4 
    },
    { id: 5, 
      name: 'Mac IOS Laptop', 
      price: 30000,
      color: 'red', 
      vendor: 'toshiba', 
      category: 'A', 
      quality: 'high', 
      image: apple1
    },
    { id: 6, 
      name: 'Dell Laptop', 
      price: 30000,
      color: 'blue', 
      vendor: 'toshiba', 
      category: 'B', 
      quality: 'medium', 
      image: apple2
    },
    { id: 7, 
      name: 'Dell laptop', 
      price: 30000, 
      color: 'yellow', 
      vendor: 'tecno', 
      category: 'C', 
      quality: 'low', 
      image: apple3
    },
    { id: 8, 
      name: 'mac Laptop',
      price: 30000, 
      color: 'green', 
      vendor: 'hp', 
      category: 'A', 
      quality: 'medium', 
      image: apple4
    },
    { id: 9, 
      name: 'Dell Dual Monitor Stand', 
      price: 60000,
      color: 'red', 
      vendor: 'toshiba', 
      category: 'A', 
      quality: 'high', 
      image: monitor1
    },
    { id: 10, 
      name: 'Satechi Apple & PC Electronic', 
      price: 60000,
      color: 'blue', 
      vendor: 'apple', 
      category: 'B', 
      quality: 'medium', 
      image: monitor2
    },
    { id: 11, 
      name: 'Monitor Andrid', 
      price: 60000, 
      color: 'yellow', 
      vendor: 'toshiba', 
      category: 'C', 
      quality: 'low', 
      image: monitor3
    },
    { id: 12, 
      name: 'Ultrawide Monitor',
      price: 160000, 
      color: 'green', 
      vendor: 'hp', 
      category: 'A', 
      quality: 'medium', 
      image: monitor4
    },
    { id: 13, 
      name: 'Mesh Office Chair', 
      price: 60000,
      color: 'red', 
      vendor: 'toshiba', 
      category: 'A', 
      quality: 'high', 
      image: chair1
    },
    { id: 14, 
      name: 'Vonesse Gaming Chair', 
      price: 60000,
      color: 'blue', 
      vendor: 'apple', 
      category: 'B', 
      quality: 'medium', 
      image: chair2
    },
    { id: 15, 
      name: 'Chefsel Online Koufen', 
      price: 60000, 
      color: 'yellow', 
      vendor: 'tecno', 
      category: 'C', 
      quality: 'low', 
      image: chair3
    },
    { id: 16, 
      name: 'mac Laptop',
      price: 60000, 
      color: 'green', 
      vendor: 'hp', 
      category: 'A', 
      quality: 'medium', 
      image: chair4
    },
    { id: 17, 
      name: 'Gold MacBook Air Accessories', 
      price: 55000,
      color: 'red', 
      vendor: 'hp', 
      category: 'A', 
      quality: 'high', 
      image: acc1
    },
    { id: 18, 
      name: 'Gaming PC', 
      price: 55000,
      color: 'blue', 
      vendor: 'toshiba', 
      category: 'B', 
      quality: 'medium', 
      image: acc2
    },
  { id: 19, 
    name: 'Fifine Gaming PC', 
    price: 55000, 
    color: 'yellow', 
    vendor: 'tecno', 
    category: 'C', 
    quality: 'low', 
    image: acc3
  },
  { id: 20, 
    name: 'EMeet 1080P Webcam',
    price: 30000, 
    color: 'green', 
    vendor: 'hp', 
    category: 'A', 
    quality: 'medium', 
    image: acc4
  },
  { id: 21, 
    name: 'Ninja Dragon RGB Computer Gaming', 
    price: 60000,
    color: 'red', 
    vendor: 'hp', 
    category: 'A', 
    quality: 'high', 
    image: audio1
  },
  { id: 22, 
    name: 'Audio Engine Wireless Bluetooth', 
    price: 20000,
    color: 'blue', 
    vendor: 'apple', 
    category: 'B', 
    quality: 'medium', 
    image: audio2
  },
  { id: 23, 
    name: 'Akai Professional MPD 218 USB MIDI', 
    price: 20000, 
    color: 'yellow', 
    vendor: 'tecno', 
    category: 'C', 
    quality: 'low', 
    image: audio3
  },
  { id: 24, 
    name: 'Ear Headphone',
    price: 30000, 
    color: 'green', 
    vendor: 'hp', 
    category: 'A', 
    quality: 'medium', 
    image: audio4
  },
  { id: 25,
    name: 'Workstation Setup', 
    price: 60000,
    color: 'red', 
    vendor: 'hp', 
    category: 'A', 
    quality: 'high', 
    image: monitor5
  },
  { id: 26, 
    name: 'A2 Beautiful Workstaion', 
    price: 60000,
    color: 'blue', 
    vendor: 'apple', 
    category: 'B', 
    quality: 'medium', 
    image: monitor6
  },
  { id: 27, 
    name: 'Imac Accessories', 
    price: 60000, 
    color: 'yellow', 
    vendor: 'tecno', 
    category: 'C', 
    quality: 'low', 
    image: monitor7
  },
  { id: 28, 
    name: 'Tech Product and Accessories',
    price: 60000, 
    color: 'green', 
    vendor: 'hp', 
    category: 'A', 
    quality: 'medium', 
    image: monitor8
  },
];

 